# Generated by Django 4.2.6 on 2023-10-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtopics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
