# Generated by Django 4.2.6 on 2023-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtopics', '0002_subtopic_slug_alter_subtopic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
