# Generated by Django 4.2.6 on 2023-10-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_slug'),
        ('subtopics', '0003_alter_subtopic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'slug')},
        ),
    ]
